### ISSUE TITLE
有些引用不能简单加.vue

### ISSUE THREAD

**Issue by StepToTop** [BryanAdamss/add-vue-suffix#1]
比如说我代码里写着
@/components/xxx
但是实际上引用的是
@/components/xxx/index.vue

**Comment by BryanAdamss** [comment]
嗯，这一块的确不好处理。
其实现在应该是可以解析出`@/components/xxx`是引用的`@/components/xxx/index.vue`文件的，但是现在是用正则替换的，拿到的是前者，然后在后面直接加上`.vue`后缀的，逻辑还需要优化下😂；

ps: 我们现在在项目里会强制要求入口组件和上层目录保持同名，例如`/abc/Button`的入口文件是`/abc/Button/Button.vue`组件。太多index在项目里不好查找、区分，必须结合路径来区分😂😂😂

**Comment by StepToTop** [comment]
那我看下吧😂

确实规范很重要QAQ

**Comment by BryanAdamss** [comment]
fixed issue with https://github.com/BryanAdamss/add-vue-suffix/blob/main/CHANGELOG.md
