### ISSUE TITLE
执行命令之后未生效

### ISSUE THREAD

**Issue by AmbitionJs** [BryanAdamss/add-vue-suffix#3]
报错信息：
![image](https://user-images.githubusercontent.com/45837094/140673996-07b7107c-5f51-4bdf-922c-830af177b4e4.png)

js文件内容：
``` 
module.exports = {
  resolve: {
    alias: {
      '.git': path.resolve(__dirname, './.git'),
      docker: path.resolve(__dirname, './docker'),
      node_modules: path.resolve(__dirname, './node_modules'),
      packages: path.resolve(__dirname, './packages'),
      public: path.resolve(__dirname, './public'),
      src: path.resolve(__dirname, './src'),
      tests: path.resolve(__dirname, './tests'),
      '@': path.resolve(__dirname, './src'),
      vue$: 'vue/dist/vue.runtime.esm.js',
      '@wxwork': path.resolve(__dirname, './src'),
      '@api': path.resolve(__dirname, './src/api'),
      '@api-crm': path.resolve(__dirname, './src/api-crm'),
      '@components': path.resolve(__dirname, './src/components'),
      '@config': path.resolve(__dirname, './src/config'),
      '@plugins': path.resolve(__dirname, './src/plugins'),
      '@utils': path.resolve(__dirname, './src/utils'),
      '@store': path.resolve(__dirname, './src/store'),
      '@router': path.resolve(__dirname, './src/router'),
      '@styles': path.resolve(__dirname, './src/styles'),
      '@assets': path.resolve(__dirname, './src/assets'),
      '@views': path.resolve(__dirname, './src/views'),
      '@ajax': path.resolve(__dirname, './src/plugins/httpClient/WrappedFetch.ts'),
      '@mk-RcCharts': path.resolve(__dirname, './packages/mk-RcCharts/src/components/index.js')
    }
  }
}
```

执行的脚本：npx add-vue-suffix --resolveConifg ./resolve.js

**Comment by BryanAdamss** [comment]
> 报错信息： ![image](https://user-images.githubusercontent.com/45837094/140673996-07b7107c-5f51-4bdf-922c-830af177b4e4.png)
> 
> js文件内容：
> 
> ```
> module.exports = {
>   resolve: {
>     alias: {
>       '.git': path.resolve(__dirname, './.git'),
>       docker: path.resolve(__dirname, './docker'),
>       node_modules: path.resolve(__dirname, './node_modules'),
>       packages: path.resolve(__dirname, './packages'),
>       public: path.resolve(__dirname, './public'),
>       src: path.resolve(__dirname, './src'),
>       tests: path.resolve(__dirname, './tests'),
>       '@': path.resolve(__dirname, './src'),
>       vue$: 'vue/dist/vue.runtime.esm.js',
>       '@wxwork': path.resolve(__dirname, './src'),
>       '@api': path.resolve(__dirname, './src/api'),
>       '@api-crm': path.resolve(__dirname, './src/api-crm'),
>       '@components': path.resolve(__dirname, './src/components'),
>       '@config': path.resolve(__dirname, './src/config'),
>       '@plugins': path.resolve(__dirname, './src/plugins'),
>       '@utils': path.resolve(__dirname, './src/utils'),
>       '@store': path.resolve(__dirname, './src/store'),
>       '@router': path.resolve(__dirname, './src/router'),
>       '@styles': path.resolve(__dirname, './src/styles'),
>       '@assets': path.resolve(__dirname, './src/assets'),
>       '@views': path.resolve(__dirname, './src/views'),
>       '@ajax': path.resolve(__dirname, './src/plugins/httpClient/WrappedFetch.ts'),
>       '@mk-RcCharts': path.resolve(__dirname, './packages/mk-RcCharts/src/components/index.js')
>     }
>   }
> }
> ```
> 
> 执行的脚本：npx add-vue-suffix --resolveConifg ./resolve.js

通过本地安装的形式，能成功吗？看报错是配置没读取到，可能npx场景有异常，我要排查下

**Comment by BryanAdamss** [comment]
@AmbitionJs  
我本地用npx测试了下，没发现问题；
您发的配置文件是完整的吗？我看似乎没有引用`const path = require('path')`😂
抱歉，应该是我的文档误导你了，我来调整下

**Comment by BryanAdamss** [comment]
> @AmbitionJs 我本地用npx测试了下，没发现问题； 您发的配置文件是完整的吗？我看似乎没有引用`const path = require('path')`😂 抱歉，应该是我的文档误导你了，我来调整下
----
c44c5c65b2acc379af3ecdc97ae9e5583b916779
已经调整文档并添加了报错信息
